[package]
name = "cloudwatch-read-logs"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-types = "1.3.3"
chrono = "0.4.38"
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-cloudwatchlogs = "1.60.0"
tokio = { version = "1", features = ["full"] }
